version: '3.8'

services:
  postgres:
    container_name: 'postgres-test-budget'
    image: 'postgres:9.6'
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - test-budget-net
    ports:
      - 45533:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  api:
    container_name: "test-budget-api"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: 'test-budget-api'
    ports:
      - 8080:8080
    networks:
      - test-budget-net
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

networks:
  test-budget-net:
    driver: bridge